version: '3'
services:
  spambot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  whatsapp-http-api:
    image: devlikeapro/whatsapp-http-api
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
